### ISSUE TITLE
Hide wholesale registration prompts from wholesalers

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#77]
If someone's already a wholesaler, we shouldn't be showing them any requests to register as one.

**Comment by d4mation** [comment]
This actually should already be taken care of. I put a bunch of checks in
for it.

Is there a prompt in particular that is still showing for wholesale users?

**Comment by brashrebel** [comment]
@BigActual do you know exactly where these prompts are? Can you confirm that something is showing to wholesalers that shouldn't be and describe where it is please?

**Comment by BigActual** [comment]
Yes, upon completing the registration process as myself, I was still receiving the prompt on the shop page. Verified today, 12/16.

**Comment by d4mation** [comment]
I see you tried to make a User under the User Name `theoptimyst`, but haven't completed the Activation Process. That could be the problem. 

Once you fill out the form, it tells you that it will send you an Activation Email. Once you click that link in the email, it takes you to the site, thanks you, and gives you a randomly generated password. From there, if you log in, it should hide all prompts.

**Comment by BigActual** [comment]
You are correct. After consideration, I suspect that there are several workflow issues that are occurring, which present this as a symptom. Because I was already logged in as a user, I couldn't complete the process without creating a new user. In addition the new user registration process includes an email that must be acted upon. The email arrives way out of sequence and conveys a message disjointed from the actual process of approval. I'll close this, and open separate issues.
