### ISSUE TITLE
Only two of four books appear on the books archive page

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#9]
http://kidniche-com.realbig.staging.wpengine.com/books/ should show all the books. Hmmm. interesting that it doesn't.

**Comment by joelworsham** [comment]
The reason for this is that you don't have a "Product Link" chosen for for "My Whole Self Before YOU -- The Prayer Guide".

It seems that a product link would be required, because we decided for the archive to show the product description and image instead of the book CPT itself. I can modify this if you want, just let me know what you want.

**Comment by BigActual** [comment]
Got it. Thanks
